### ISSUE TITLE
Errors running make in Linux

### ISSUE THREAD

**Issue by ashokbugude** [Norman0406/OpenSkeletonFitting#2]
I am trying to build in Linux 16.04

I get below errors after commenting minPackLibrary

Scanning dependencies of target OpenSF
[  2%] Building CXX object OpenSF/CMakeFiles/OpenSF.dir/Exception.cpp.o
In file included from /home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/Module.h:25:0,
                 from /home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/precompiled.h:23,
                 from /home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/Exception.cpp:22:
/home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/ModuleInput.h: In constructor ‘osf::ModuleInput<T>::ModuleInput(int, const T_&)’:
/home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/ModuleInput.h:47:53: error: must #include <typeinfo> before using typeid
     LOG << "new input [type, index]: \"" << typeid(T).name() << "\", " << index
                                                     ^
In file included from /home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/Module.h:26:0,
                 from /home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/precompiled.h:23,
                 from /home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/Exception.cpp:22:
/home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/ModuleOutput.h: In constructor ‘osf::ModuleOutput<T>::ModuleOutput(int, T_)’:
/home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/ModuleOutput.h:47:54: error: must #include <typeinfo> before using typeid
     LOG << "new output [type, index]: \"" << typeid(T).name() << "\", " << inde
                                                      ^
In file included from /home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/precompiled.h:24:0,
                 from /home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/Exception.cpp:22:
/home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/Factory.h: At global scope:
/home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/Factory.h:41:32: error: ‘type_info’ does not name a type
   static T\* createByType(const type_info& info, System\* sys) {
                                ^
/home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/Factory.h:60:33: error: ‘type_info’ does not name a type
   static T\* iCreateByType(const type_info&, System\* sys);
                                 ^
/home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/Factory.h: In static member function ‘static T\* osf::Factory<T>::createByType(const int&, osf::System_)’:
/home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/Factory.h:42:39: error: request for member ‘name’ in ‘info’, which is of non-class type ‘const int’
    LOG << "creating object: " << info.name() << ENDL;
                                       ^
/home/zayyon/Downloads/OpenSkeletonFitting-master/OpenSF/Factory.h:50:50: error: request for member ‘name’ in ‘info’, which is of non-class type ‘const int’
     ERR << "could not create object: \"" << info.name() << "\"" << ENDL;
                                                  ^
OpenSF/CMakeFiles/OpenSF.dir/build.make:62: recipe for target 'OpenSF/CMakeFiles/OpenSF.dir/Exception.cpp.o' failed
make[2]: *_\* [OpenSF/CMakeFiles/OpenSF.dir/Exception.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'OpenSF/CMakeFiles/OpenSF.dir/all' failed
make[1]: **\* [OpenSF/CMakeFiles/OpenSF.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: **\* [all] Error 2
